language: python
matrix:
  include:
  - os: linux
    python: 3.8
    env:
    - TOXENV=flake8,spell,twine
  - os: linux
    python: 3.8
    env:
    - TOXENV=docs
  - os: linux
    python: 3.8
    env:
    - TOXENV=mypy
  - os: linux
    python: 2.7
    env:
    - TOXENV=py27-linux_non_root,codecov
  - os: linux
    dist: xenial
    python: 3.8
    env:
    - TOXENV=py38-linux_non_root,codecov
  - os: linux
    python: pypy
    env:
    - TOXENV=pypy-linux_non_root,codecov
  - os: linux
    python: pypy3
    env:
    - TOXENV=pypy3-linux_non_root,codecov
  - os: osx
    language: generic
    env:
    - TOXENV=py27-bsd_non_root,codecov
  - language: python
    dist: trusty
    python: 2.7
    env:
    - TOXENV=py27-linux_root,codecov
  - os: linux
    python: pypy
    env:
    - TOXENV=pypy-linux_root,codecov
  - os: linux
    python: pypy3
    env:
    - TOXENV=pypy3-linux_root,codecov
  - language: python
    dist: trusty
    python: 3.4
    env:
    - TOXENV=py34-linux_root,codecov
  - language: python
    dist: trusty
    python: 3.5
    env:
    - TOXENV=py35-linux_root,codecov
  - language: python
    dist: trusty
    python: 3.6
    env:
    - TOXENV=py36-linux_root,codecov
  - language: python
    dist: xenial
    python: 3.7
    env:
    - TOXENV=py37-linux_root,codecov
  - language: python
    dist: xenial
    python: 3.8
    env:
    - TOXENV=py38-linux_root,codecov
  - os: linux
    python: 2.7
    virtualenv:
      system_site_packages: true
    env:
    - SCAPY_SUDO=sudo SCAPY_USE_PCAPDNET=yes TOXENV=py27-pcapdnet_root,codecov
  - language: python
    dist: trusty
    python: 3.6
    env:
    - SCAPY_SUDO=sudo TOXENV=py36-isotp_kernel_module,codecov
  - os: osx
    language: generic
    env:
    - TOXENV=py27-bsd_root,codecov
  - os: osx
    language: generic
    env:
    - SCAPY_SUDO=sudo SCAPY_USE_PCAPDNET=yes TOXENV=py27-pcapdnet_root,codecov
  - os: osx
    language: generic
    env:
    - TOXENV=py36-bsd_non_root,py36-bsd_root,codecov
install:
- bash .config/travis/install.sh
- python -c "from scapy.all import conf; print(repr(conf))"
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
