language: python
dist: bionic
cache:
  directories:
  - $HOME/.cache/pip
  - .tox
jobs:
  include:
  - os: linux
    python: 2.7
    env:
    - TOXENV=py27-linux_root,codecov
  - os: linux
    python: pypy2
    env:
    - TOXENV=pypy-linux_root,codecov
  - os: linux
    python: pypy3
    env:
    - TOXENV=pypy3-linux_root,codecov
  - os: linux
    python: 3.8
    env:
    - TOXENV=py38-linux_root,codecov
  - os: osx
    osx_image: xcode9.3
    language: shell
    before_install:
    - python --version
    - pip install --upgrade --ignore-installed --user pip tox setuptools
    env:
    - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
  - os: osx
    osx_image: xcode10.2
    language: shell
    before_install:
    - python3 --version
    - pip3 install --upgrade --ignore-installed pip tox setuptools
    env:
    - TOXENV=py37-bsd_non_root,py37-bsd_root,codecov
  - os: linux
    python: 3.8
    env:
    - TOXENV=py38-isotp_kernel_module,codecov
  - os: linux
    python: 3.8
    env:
    - SCAPY_USE_LIBPCAP=yes TOXENV=py38-linux_root,codecov
  - os: linux
    python: 3.8
    env:
    - SCAPY_PY_OPTS="-Werror -X tracemalloc" TOXENV=py38-linux_root
install:
- bash .config/ci/install.sh
- python -c "from scapy.all import conf; print(repr(conf))"
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
